<?php

return [
    "title" => "系统配置",
    "url" => "settings/setting",
    "method" => "GET",
    "slug" => $slug,
    "icon" => "icon-zidongxiufu",
    "listorder" => 1000,
    "menu_show" => 1,
    "remark" => "",
    "children" => [
        [
            "title" => "系统设置",
            "url" => "settings/setting",
            "method" => "GET",
            "slug" => "admin.settings.setting",
            "icon" => "icon-setup",
            "listorder" => 5,
            "menu_show" => 1,
            "children" => [
                [
                    "title" => "系统设置",
                    "url" => "settings/setting",
                    "method" => "GET",
                    "slug" => "admin.settings.setting",
                    "menu_show" => 0,
                    "listorder" => 5,
                ],
                [
                    "title" => "系统设置",
                    "url" => "settings/setting",
                    "method" => "POST",
                    "slug" => "admin.settings.setting-post",
                    "menu_show" => 0,
                    "listorder" => 15,
                ],
            ],
        ],
        [
            "title" => "配置管理",
            "url" => "settings/index",
            "method" => "GET",
            "slug" => "admin.settings.index",
            "icon" => "icon-apartment",
            "listorder" => 15,
            "menu_show" => 1,
            "children" => [
                [
                    "title" => "系统设置",
                    "url" => "settings/index",
                    "method" => "GET",
                    "slug" => "admin.settings.index",
                    "menu_show" => 0,
                    "listorder" => 5,
                ],
                [
                    "title" => "系统设置",
                    "url" => "settings/index",
                    "method" => "POST",
                    "slug" => "admin.settings.index-post",
                    "menu_show" => 0,
                    "listorder" => 10,
                ],
                [
                    "title" => "全部配置",
                    "url" => "settings/all",
                    "method" => "GET",
                    "slug" => "admin.settings.all",
                    "menu_show" => 0,
                    "listorder" => 15,
                ],
                [
                    "title" => "全部配置",
                    "url" => "settings/all",
                    "method" => "POST",
                    "slug" => "admin.settings.all-post",
                    "menu_show" => 0,
                    "listorder" => 20,
                ],
                [
                    "title" => "新增配置",
                    "url" => "settings/add",
                    "method" => "GET",
                    "slug" => "admin.settings.add",
                    "menu_show" => 0,
                    "listorder" => 25,
                ],
                [
                    "title" => "新增配置",
                    "url" => "settings/add",
                    "method" => "POST",
                    "slug" => "admin.settings.add-post",
                    "menu_show" => 0,
                    "listorder" => 30,
                ],
                [
                    "title" => "编辑配置",
                    "url" => "settings/edit",
                    "method" => "GET",
                    "slug" => "admin.settings.edit",
                    "menu_show" => 0,
                    "listorder" => 35,
                ],
                [
                    "title" => "编辑配置",
                    "url" => "settings/edit",
                    "method" => "POST",
                    "slug" => "admin.settings.edit-post",
                    "menu_show" => 0,
                    "listorder" => 40,
                ],
                [
                    "title" => "删除配置",
                    "url" => "settings/del",
                    "method" => "POST",
                    "slug" => "admin.settings.del-post",
                    "menu_show" => 0,
                    "listorder" => 45,
                ],
                [
                    "title" => "配置排序",
                    "url" => "settings/listorder",
                    "method" => "POST",
                    "slug" => "admin.settings.listorder-post",
                    "menu_show" => 0,
                    "listorder" => 50,
                ],
                [
                    "title" => "设置状态",
                    "url" => "settings/setstate",
                    "method" => "POST",
                    "slug" => "admin.settings.setstate-post",
                    "menu_show" => 0,
                    "listorder" => 55,
                ],
            ],
        ],
    ],
];
